### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [Trampoline-CX/cubes#92]
It has been noticed that while using chromaui/action@v1 your projectToken t00yilwkcv is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by alexbchr** [comment]
Thanks @raima-zachariah for the notice! I created a PR fixing this and the Chromatic token was regenerated so it is no longer the one leaked.
